# Configuración del puerto del servidor (por defecto es 8080)
server.port=8080

# Conexión a la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/atlas_gym?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configuración de Hibernate (Crea o actualiza las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
